CREATE TABLE Categories(
   Cat_Name    VARCHAR(33) NOT NULL PRIMARY KEY
  ,Category_ID INTEGER  NOT NULL
);
UPDATE Categories SET Cat_Name = 'Lettuce - Spring Mix',Category_ID = 1270934228 WHERE Cat_Name= 'Lettuce - Spring Mix';
UPDATE Categories SET Cat_Name = 'Longos - Cheese Tortellini',Category_ID = 4840397252 WHERE Cat_Name= 'Longos - Cheese Tortellini';
UPDATE Categories SET Cat_Name = 'Soup - Campbells - Tomato',Category_ID = 0967002052 WHERE Cat_Name= 'Soup - Campbells - Tomato';
UPDATE Categories SET Cat_Name = 'Wine - Jaboulet Cotes Du Rhone',Category_ID = 5516395305 WHERE Cat_Name= 'Wine - Jaboulet Cotes Du Rhone';
UPDATE Categories SET Cat_Name = 'Gelatine Powder',Category_ID = 3393610511 WHERE Cat_Name= 'Gelatine Powder';
UPDATE Categories SET Cat_Name = 'Cabbage - Nappa',Category_ID = 1836856717 WHERE Cat_Name= 'Cabbage - Nappa';
UPDATE Categories SET Cat_Name = 'Cookie - Dough Variety',Category_ID = 9655307565 WHERE Cat_Name= 'Cookie - Dough Variety';
UPDATE Categories SET Cat_Name = 'Beer - Corona',Category_ID = 7099429825 WHERE Cat_Name= 'Beer - Corona';
UPDATE Categories SET Cat_Name = 'Pepper - Gypsy Pepper',Category_ID = 4366741067 WHERE Cat_Name= 'Pepper - Gypsy Pepper';
UPDATE Categories SET Cat_Name = 'Glass - Wine, Plastic, Clear 5 Oz',Category_ID = 2126377504 WHERE Cat_Name= 'Glass - Wine, Plastic, Clear 5 Oz';
UPDATE Categories SET Cat_Name = 'Vinegar - Sherry',Category_ID = 2225448140 WHERE Cat_Name= 'Vinegar - Sherry';
UPDATE Categories SET Cat_Name = 'Pesto - Primerba, Paste',Category_ID = 4296314424 WHERE Cat_Name= 'Pesto - Primerba, Paste';
UPDATE Categories SET Cat_Name = 'Tart Shells - Barquettes, Savory',Category_ID = 9323247812 WHERE Cat_Name= 'Tart Shells - Barquettes, Savory';
UPDATE Categories SET Cat_Name = 'Anchovy Paste - 56 G Tube',Category_ID = 9599830415 WHERE Cat_Name= 'Anchovy Paste - 56 G Tube';
UPDATE Categories SET Cat_Name = 'Longos - Penne With Pesto',Category_ID = 3858987573 WHERE Cat_Name= 'Longos - Penne With Pesto';
UPDATE Categories SET Cat_Name = 'Soup - Knorr, Classic Can. Chili',Category_ID = 7303394257 WHERE Cat_Name= 'Soup - Knorr, Classic Can. Chili';
UPDATE Categories SET Cat_Name = 'Wine - Chardonnay Mondavi',Category_ID = 6712694663 WHERE Cat_Name= 'Wine - Chardonnay Mondavi';
UPDATE Categories SET Cat_Name = 'Quinoa',Category_ID = 7191200766 WHERE Cat_Name= 'Quinoa';
UPDATE Categories SET Cat_Name = 'Pasta - Lasagne, Fresh',Category_ID = 4833751801 WHERE Cat_Name= 'Pasta - Lasagne, Fresh';
UPDATE Categories SET Cat_Name = 'Wine - Chateau Bonnet',Category_ID = 9305887104 WHERE Cat_Name= 'Wine - Chateau Bonnet';
UPDATE Categories SET Cat_Name = 'Flour - Buckwheat, Dark',Category_ID = 7935235384 WHERE Cat_Name= 'Flour - Buckwheat, Dark';
UPDATE Categories SET Cat_Name = 'Turkey - Breast, Double',Category_ID = 4310850197 WHERE Cat_Name= 'Turkey - Breast, Double';
UPDATE Categories SET Cat_Name = 'Oil - Cooking Spray',Category_ID = 8465282072 WHERE Cat_Name= 'Oil - Cooking Spray';
UPDATE Categories SET Cat_Name = 'Wonton Wrappers',Category_ID = 1044442867 WHERE Cat_Name= 'Wonton Wrappers';
UPDATE Categories SET Cat_Name = 'Wine - Placido Pinot Grigo',Category_ID = 0417382332 WHERE Cat_Name= 'Wine - Placido Pinot Grigo';
UPDATE Categories SET Cat_Name = 'Cheese - Grie Des Champ',Category_ID = 6181814183 WHERE Cat_Name= 'Cheese - Grie Des Champ';
UPDATE Categories SET Cat_Name = 'Lemonade - Black Cherry, 591 Ml',Category_ID = 1121139787 WHERE Cat_Name= 'Lemonade - Black Cherry, 591 Ml';
UPDATE Categories SET Cat_Name = 'Lamb - Ground',Category_ID = 6263552735 WHERE Cat_Name= 'Lamb - Ground';
UPDATE Categories SET Cat_Name = 'Bagel - Ched Chs Presliced',Category_ID = 4692469749 WHERE Cat_Name= 'Bagel - Ched Chs Presliced';
UPDATE Categories SET Cat_Name = 'Taro Leaves',Category_ID = 0890341346 WHERE Cat_Name= 'Taro Leaves';
UPDATE Categories SET Cat_Name = 'Soup - Campbells Chili Veg',Category_ID = 0728308401 WHERE Cat_Name= 'Soup - Campbells Chili Veg';
UPDATE Categories SET Cat_Name = 'Wine - Montecillo Rioja Crianza',Category_ID = 4308253357 WHERE Cat_Name= 'Wine - Montecillo Rioja Crianza';
UPDATE Categories SET Cat_Name = 'Bouillion - Fish',Category_ID = 9762949617 WHERE Cat_Name= 'Bouillion - Fish';
UPDATE Categories SET Cat_Name = 'Sunflower Seed Raw',Category_ID = 3414096374 WHERE Cat_Name= 'Sunflower Seed Raw';
UPDATE Categories SET Cat_Name = 'Chutney Sauce - Mango',Category_ID = 4180315882 WHERE Cat_Name= 'Chutney Sauce - Mango';
UPDATE Categories SET Cat_Name = 'Island Oasis - Peach Daiquiri',Category_ID = 5554489338 WHERE Cat_Name= 'Island Oasis - Peach Daiquiri';
UPDATE Categories SET Cat_Name = 'Pie Box - Cello Window 2.5',Category_ID = 9886336978 WHERE Cat_Name= 'Pie Box - Cello Window 2.5';
UPDATE Categories SET Cat_Name = 'Chicken - White Meat, No Tender',Category_ID = 1773721097 WHERE Cat_Name= 'Chicken - White Meat, No Tender';
UPDATE Categories SET Cat_Name = 'Syrup - Kahlua Chocolate',Category_ID = 2156940630 WHERE Cat_Name= 'Syrup - Kahlua Chocolate';
UPDATE Categories SET Cat_Name = 'Sprouts Dikon',Category_ID = 7801687302 WHERE Cat_Name= 'Sprouts Dikon';
UPDATE Categories SET Cat_Name = 'Mushroom - White Button',Category_ID = 8909339896 WHERE Cat_Name= 'Mushroom - White Button';
UPDATE Categories SET Cat_Name = 'Pork - Tenderloin, Fresh',Category_ID = 7255425607 WHERE Cat_Name= 'Pork - Tenderloin, Fresh';
UPDATE Categories SET Cat_Name = 'Clams - Canned',Category_ID = 8410834081 WHERE Cat_Name= 'Clams - Canned';
UPDATE Categories SET Cat_Name = 'Cardamon Ground',Category_ID = 2206905515 WHERE Cat_Name= 'Cardamon Ground';
UPDATE Categories SET Cat_Name = 'Parsley - Fresh',Category_ID = 6324614387 WHERE Cat_Name= 'Parsley - Fresh';
UPDATE Categories SET Cat_Name = 'Rabbit - Frozen',Category_ID = 4748805595 WHERE Cat_Name= 'Rabbit - Frozen';
UPDATE Categories SET Cat_Name = 'Beef - Tenderloin Tails',Category_ID = 8843812696 WHERE Cat_Name= 'Beef - Tenderloin Tails';
UPDATE Categories SET Cat_Name = 'Beets - Golden',Category_ID = 7378954667 WHERE Cat_Name= 'Beets - Golden';
UPDATE Categories SET Cat_Name = 'Capon - Whole',Category_ID = 6056667723 WHERE Cat_Name= 'Capon - Whole';
UPDATE Categories SET Cat_Name = 'Pears - Anjou',Category_ID = 3008042007 WHERE Cat_Name= 'Pears - Anjou';
UPDATE Categories SET Cat_Name = 'Mushroom - Shitake, Fresh',Category_ID = 4455821848 WHERE Cat_Name= 'Mushroom - Shitake, Fresh';
UPDATE Categories SET Cat_Name = 'Wine - Barossa Valley Estate',Category_ID = 8672204085 WHERE Cat_Name= 'Wine - Barossa Valley Estate';
UPDATE Categories SET Cat_Name = 'Chinese Foods - Pepper Beef',Category_ID = 4607934917 WHERE Cat_Name= 'Chinese Foods - Pepper Beef';
UPDATE Categories SET Cat_Name = 'Puree - Pear',Category_ID = 4256118020 WHERE Cat_Name= 'Puree - Pear';
UPDATE Categories SET Cat_Name = 'Rosemary - Primerba, Paste',Category_ID = 5354762782 WHERE Cat_Name= 'Rosemary - Primerba, Paste';
UPDATE Categories SET Cat_Name = 'Beef - Tender Tips',Category_ID = 5249366775 WHERE Cat_Name= 'Beef - Tender Tips';
UPDATE Categories SET Cat_Name = 'Table Cloth 53x69 White',Category_ID = 1934270393 WHERE Cat_Name= 'Table Cloth 53x69 White';
UPDATE Categories SET Cat_Name = 'Sproutsmustard Cress',Category_ID = 0382555856 WHERE Cat_Name= 'Sproutsmustard Cress';
UPDATE Categories SET Cat_Name = 'Veal - Inside Round / Top, Lean',Category_ID = 9484787533 WHERE Cat_Name= 'Veal - Inside Round / Top, Lean';
UPDATE Categories SET Cat_Name = 'Tomatoes Tear Drop',Category_ID = 4260536818 WHERE Cat_Name= 'Tomatoes Tear Drop';
UPDATE Categories SET Cat_Name = 'Maintenance Removal Charge',Category_ID = 7327037950 WHERE Cat_Name= 'Maintenance Removal Charge';
UPDATE Categories SET Cat_Name = 'Veal - Insides, Grains',Category_ID = 0209075872 WHERE Cat_Name= 'Veal - Insides, Grains';
UPDATE Categories SET Cat_Name = 'Island Oasis - Wildberry',Category_ID = 2042863130 WHERE Cat_Name= 'Island Oasis - Wildberry';
UPDATE Categories SET Cat_Name = 'Pepper - Black, Whole',Category_ID = 4396112394 WHERE Cat_Name= 'Pepper - Black, Whole';
UPDATE Categories SET Cat_Name = 'Sprite, Diet - 355ml',Category_ID = 7547252125 WHERE Cat_Name= 'Sprite, Diet - 355ml';
UPDATE Categories SET Cat_Name = 'Glass Clear 7 Oz Xl',Category_ID = 9108952140 WHERE Cat_Name= 'Glass Clear 7 Oz Xl';
UPDATE Categories SET Cat_Name = 'Rice Pilaf, Dry,package',Category_ID = 3138327192 WHERE Cat_Name= 'Rice Pilaf, Dry,package';
UPDATE Categories SET Cat_Name = 'Chutney Sauce',Category_ID = 1808258118 WHERE Cat_Name= 'Chutney Sauce';
UPDATE Categories SET Cat_Name = 'Flounder - Fresh',Category_ID = 3984463960 WHERE Cat_Name= 'Flounder - Fresh';
UPDATE Categories SET Cat_Name = 'Pasta - Lasagne, Fresh',Category_ID = 4975054515 WHERE Cat_Name= 'Pasta - Lasagne, Fresh';
UPDATE Categories SET Cat_Name = 'Creme De Cacao White',Category_ID = 9121310629 WHERE Cat_Name= 'Creme De Cacao White';
UPDATE Categories SET Cat_Name = 'Ecolab - Ster Bac',Category_ID = 1817249649 WHERE Cat_Name= 'Ecolab - Ster Bac';
UPDATE Categories SET Cat_Name = 'Turkey - Breast, Bone - In',Category_ID = 5205985267 WHERE Cat_Name= 'Turkey - Breast, Bone - In';
UPDATE Categories SET Cat_Name = 'Salmon Steak - Cohoe 8 Oz',Category_ID = 2586956427 WHERE Cat_Name= 'Salmon Steak - Cohoe 8 Oz';
UPDATE Categories SET Cat_Name = 'Mayonnaise - Individual Pkg',Category_ID = 8185546894 WHERE Cat_Name= 'Mayonnaise - Individual Pkg';
UPDATE Categories SET Cat_Name = 'Poppy Seed',Category_ID = 2324453886 WHERE Cat_Name= 'Poppy Seed';
UPDATE Categories SET Cat_Name = 'Sauce - Marinara',Category_ID = 0206681720 WHERE Cat_Name= 'Sauce - Marinara';
UPDATE Categories SET Cat_Name = 'Dc - Frozen Momji',Category_ID = 0770823343 WHERE Cat_Name= 'Dc - Frozen Momji';
UPDATE Categories SET Cat_Name = 'Water - San Pellegrino',Category_ID = 5226637136 WHERE Cat_Name= 'Water - San Pellegrino';
UPDATE Categories SET Cat_Name = 'Steampan - Half Size Shallow',Category_ID = 3502707197 WHERE Cat_Name= 'Steampan - Half Size Shallow';
UPDATE Categories SET Cat_Name = 'Chocolate - Pistoles, White',Category_ID = 6750582664 WHERE Cat_Name= 'Chocolate - Pistoles, White';
UPDATE Categories SET Cat_Name = 'Bagels Poppyseed',Category_ID = 0667029664 WHERE Cat_Name= 'Bagels Poppyseed';
UPDATE Categories SET Cat_Name = 'Pork - Butt, Boneless',Category_ID = 2772235254 WHERE Cat_Name= 'Pork - Butt, Boneless';
UPDATE Categories SET Cat_Name = 'Lamb - Bones',Category_ID = 9778799180 WHERE Cat_Name= 'Lamb - Bones';
UPDATE Categories SET Cat_Name = 'Quinoa',Category_ID = 4806218286 WHERE Cat_Name= 'Quinoa';
UPDATE Categories SET Cat_Name = 'Coconut - Shredded, Sweet',Category_ID = 1411953339 WHERE Cat_Name= 'Coconut - Shredded, Sweet';
UPDATE Categories SET Cat_Name = 'Long Island Ice Tea',Category_ID = 2171467150 WHERE Cat_Name= 'Long Island Ice Tea';
UPDATE Categories SET Cat_Name = 'Ice Cream - Turtles Stick Bar',Category_ID = 7739580228 WHERE Cat_Name= 'Ice Cream - Turtles Stick Bar';
UPDATE Categories SET Cat_Name = 'Breakfast Quesadillas',Category_ID = 1198473207 WHERE Cat_Name= 'Breakfast Quesadillas';
UPDATE Categories SET Cat_Name = 'Wine - Fontanafredda Barolo',Category_ID = 2869061366 WHERE Cat_Name= 'Wine - Fontanafredda Barolo';
UPDATE Categories SET Cat_Name = 'Hagen Daza - Dk Choocolate',Category_ID = 0233870997 WHERE Cat_Name= 'Hagen Daza - Dk Choocolate';
UPDATE Categories SET Cat_Name = 'Pork - Sausage Casing',Category_ID = 4955837697 WHERE Cat_Name= 'Pork - Sausage Casing';
UPDATE Categories SET Cat_Name = 'Green Tea Refresher',Category_ID = 3524051669 WHERE Cat_Name= 'Green Tea Refresher';
UPDATE Categories SET Cat_Name = 'Oil - Margarine',Category_ID = 0809072157 WHERE Cat_Name= 'Oil - Margarine';
UPDATE Categories SET Cat_Name = 'Bread - Kimel Stick Poly',Category_ID = 9036729912 WHERE Cat_Name= 'Bread - Kimel Stick Poly';
UPDATE Categories SET Cat_Name = 'Ice Cream Bar - Hageen Daz To',Category_ID = 3145268430 WHERE Cat_Name= 'Ice Cream Bar - Hageen Daz To';
UPDATE Categories SET Cat_Name = 'Longos - Chicken Cordon Bleu',Category_ID = 2465518054 WHERE Cat_Name= 'Longos - Chicken Cordon Bleu';
UPDATE Categories SET Cat_Name = 'Rice - Long Grain',Category_ID = 4029397352 WHERE Cat_Name= 'Rice - Long Grain';
UPDATE Categories SET Cat_Name = 'Dill - Primerba, Paste',Category_ID = 4417707073 WHERE Cat_Name= 'Dill - Primerba, Paste';
UPDATE Categories SET Cat_Name = 'Pasta - Elbows, Macaroni, Dry',Category_ID = 7693562664 WHERE Cat_Name= 'Pasta - Elbows, Macaroni, Dry';
