CREATE TABLE Internal_Employees(
   First_Name  VARCHAR(13) NOT NULL PRIMARY KEY
  ,Last_Name   VARCHAR(13) NOT NULL
  ,Int_Emp_ID  INTEGER  NOT NULL
  ,Email       VARCHAR(34) NOT NULL
  ,City        VARCHAR(15) NOT NULL
  ,State       VARCHAR(14) NOT NULL
  ,Zip_Code    INTEGER  NOT NULL
  ,Dept_Name   VARCHAR(32) NOT NULL
  ,Dept_Number INTEGER  NOT NULL
  ,Company_ID  INTEGER  NOT NULL
  ,Sup_ID      INTEGER  NOT NULL
);
UPDATE Internal_Employees SET First_Name = 'Trudie',Last_Name = 'Robbins',Int_Emp_ID = 230,Email = 'trobbins0@weibo.com',City = 'Boston',State = 'Massachusetts',Zip_Code = 2208,Dept_Name = 'Business Development',Dept_Number = 6650,Company_ID = 3104705100,Sup_ID = 230 WHERE First_Name= 'Trudie';
UPDATE Internal_Employees SET First_Name = 'Kate',Last_Name = 'Kingstne',Int_Emp_ID = 231,Email = 'kkingstne1@foxnews.com',City = 'Charleston',State = 'West Virginia',Zip_Code = 25336,Dept_Name = 'Creative Services',Dept_Number = 6651,Company_ID = 3104705100,Sup_ID = 231 WHERE First_Name= 'Kate';
UPDATE Internal_Employees SET First_Name = 'Dickie',Last_Name = 'Ezzell',Int_Emp_ID = 232,Email = 'dezzell2@sfgate.com',City = 'Charleston',State = 'South Carolina',Zip_Code = 29424,Dept_Name = 'Customer Service',Dept_Number = 6652,Company_ID = 3104705100,Sup_ID = 232 WHERE First_Name= 'Dickie';
UPDATE Internal_Employees SET First_Name = 'Adara',Last_Name = 'Kohrsen',Int_Emp_ID = 233,Email = 'akohrsen3@accuweather.com',City = 'Vero Beach',State = 'Florida',Zip_Code = 32964,Dept_Name = 'Accounting',Dept_Number = 6653,Company_ID = 3104705100,Sup_ID = 233 WHERE First_Name= 'Adara';
UPDATE Internal_Employees SET First_Name = 'Darcey',Last_Name = 'Ollerenshaw',Int_Emp_ID = 234,Email = 'dollerenshaw4@ucoz.com',City = 'San Antonio',State = 'Texas',Zip_Code = 78255,Dept_Name = 'Human Resources',Dept_Number = 6654,Company_ID = 3104705100,Sup_ID = 234 WHERE First_Name= 'Darcey';
UPDATE Internal_Employees SET First_Name = 'Maighdiln',Last_Name = 'Thickpenny',Int_Emp_ID = 235,Email = 'mthickpenny5@tamu.edu',City = 'Kansas City',State = 'Missouri',Zip_Code = 64153,Dept_Name = 'Legal',Dept_Number = 6655,Company_ID = 3104705100,Sup_ID = 235 WHERE First_Name= 'Maighdiln';
UPDATE Internal_Employees SET First_Name = 'Nichole',Last_Name = 'Dishman',Int_Emp_ID = 236,Email = 'ndishman6@elegantthemes.com',City = 'Tucson',State = 'Arizona',Zip_Code = 85715,Dept_Name = 'Operations',Dept_Number = 6656,Company_ID = 3104705100,Sup_ID = 236 WHERE First_Name= 'Nichole';
UPDATE Internal_Employees SET First_Name = 'Lavena',Last_Name = 'Cutcliffe',Int_Emp_ID = 237,Email = 'lcutcliffe7@whitehouse.gov',City = 'Littleton',State = 'Colorado',Zip_Code = 80127,Dept_Name = 'Production',Dept_Number = 6657,Company_ID = 3104705100,Sup_ID = 237 WHERE First_Name= 'Lavena';
UPDATE Internal_Employees SET First_Name = 'Bea',Last_Name = 'Marrion',Int_Emp_ID = 238,Email = 'bmarrion8@purevolume.com',City = 'Tampa',State = 'Florida',Zip_Code = 33686,Dept_Name = 'Risk Management',Dept_Number = 6658,Company_ID = 3104705100,Sup_ID = 238 WHERE First_Name= 'Bea';
UPDATE Internal_Employees SET First_Name = 'Colleen',Last_Name = 'Tasch',Int_Emp_ID = 239,Email = 'ctasch9@vimeo.com',City = 'Dallas',State = 'Texas',Zip_Code = 75277,Dept_Name = 'Marketing',Dept_Number = 6659,Company_ID = 3104705100,Sup_ID = 239 WHERE First_Name= 'Colleen';
UPDATE Internal_Employees SET First_Name = 'Meade',Last_Name = 'Bockler',Int_Emp_ID = 240,Email = 'mbocklera@studiopress.com',City = 'Tyler',State = 'Texas',Zip_Code = 75799,Dept_Name = 'Sales',Dept_Number = 6660,Company_ID = 3104705100,Sup_ID = 240 WHERE First_Name= 'Meade';
UPDATE Internal_Employees SET First_Name = 'Beau',Last_Name = 'Braferton',Int_Emp_ID = 241,Email = 'bbrafertonb@un.org',City = 'Miami',State = 'Florida',Zip_Code = 33147,Dept_Name = 'Technology',Dept_Number = 6661,Company_ID = 3104705100,Sup_ID = 241 WHERE First_Name= 'Beau';
UPDATE Internal_Employees SET First_Name = 'Corny',Last_Name = 'McNally',Int_Emp_ID = 242,Email = 'cmcnallyc@princeton.edu',City = 'Augusta',State = 'Georgia',Zip_Code = 30911,Dept_Name = 'General Management',Dept_Number = 6662,Company_ID = 3104705100,Sup_ID = 242 WHERE First_Name= 'Corny';
UPDATE Internal_Employees SET First_Name = 'Halie',Last_Name = 'Morsley',Int_Emp_ID = 243,Email = 'hmorsleyd@apple.com',City = 'Milwaukee',State = 'Wisconsin',Zip_Code = 53277,Dept_Name = 'Engineering',Dept_Number = 6663,Company_ID = 3104705100,Sup_ID = 243 WHERE First_Name= 'Halie';
UPDATE Internal_Employees SET First_Name = 'Glynnis',Last_Name = 'Soppett',Int_Emp_ID = 244,Email = 'gsoppette@guardian.co.uk',City = 'Indianapolis',State = 'Indiana',Zip_Code = 46226,Dept_Name = 'Investor Relations',Dept_Number = 6664,Company_ID = 3104705100,Sup_ID = 244 WHERE First_Name= 'Glynnis';
UPDATE Internal_Employees SET First_Name = 'Alonzo',Last_Name = 'Levecque',Int_Emp_ID = 245,Email = 'alevecquef@domainmarket.com',City = 'New York City',State = 'New York',Zip_Code = 10203,Dept_Name = 'Product Management',Dept_Number = 6665,Company_ID = 3104705100,Sup_ID = 245 WHERE First_Name= 'Alonzo';
UPDATE Internal_Employees SET First_Name = 'Belicia',Last_Name = 'Bracey',Int_Emp_ID = 246,Email = 'bbraceyg@dagondesign.com',City = 'New York City',State = 'New York',Zip_Code = 10292,Dept_Name = 'Quality Assurance',Dept_Number = 6666,Company_ID = 3104705100,Sup_ID = 246 WHERE First_Name= 'Belicia';
UPDATE Internal_Employees SET First_Name = 'Jannel',Last_Name = 'Starford',Int_Emp_ID = 247,Email = 'jstarfordh@miibeian.gov.cn',City = 'Houston',State = 'Texas',Zip_Code = 77090,Dept_Name = 'Strategic Initiatives & Programs',Dept_Number = 6667,Company_ID = 3104705100,Sup_ID = 247 WHERE First_Name= 'Jannel';
UPDATE Internal_Employees SET First_Name = 'Erich',Last_Name = 'Maultby',Int_Emp_ID = 248,Email = 'emaultbyi@friendfeed.com',City = 'Minneapolis',State = 'Minnesota',Zip_Code = 55448,Dept_Name = 'Board of Directors',Dept_Number = 6668,Company_ID = 3104705100,Sup_ID = 248 WHERE First_Name= 'Erich';
UPDATE Internal_Employees SET First_Name = 'Erica',Last_Name = 'Landsbury',Int_Emp_ID = 249,Email = 'elandsburyj@ocn.ne.jp',City = 'Greensboro',State = 'North Carolina',Zip_Code = 27425,Dept_Name = 'Research and Development',Dept_Number = 6669,Company_ID = 3104705100,Sup_ID = 249 WHERE First_Name= 'Erica';
UPDATE Internal_Employees SET First_Name = 'Joanie',Last_Name = 'Padwick',Int_Emp_ID = 250,Email = 'jpadwickk@trellian.com',City = 'Shawnee Mission',State = 'Kansas',Zip_Code = 66215,Dept_Name = 'Training',Dept_Number = 6670,Company_ID = 3104705100,Sup_ID = 250 WHERE First_Name= 'Joanie';
UPDATE Internal_Employees SET First_Name = 'Tori',Last_Name = 'McGiffie',Int_Emp_ID = 251,Email = 'tmcgiffiel@nps.gov',City = 'Jacksonville',State = 'Florida',Zip_Code = 32209,Dept_Name = 'Support',Dept_Number = 6671,Company_ID = 3104705100,Sup_ID = 251 WHERE First_Name= 'Tori';
UPDATE Internal_Employees SET First_Name = 'Rosy',Last_Name = 'Trelevan',Int_Emp_ID = 252,Email = 'rtrelevanm@weebly.com',City = 'Lubbock',State = 'Texas',Zip_Code = 79491,Dept_Name = 'Asset Management',Dept_Number = 6672,Company_ID = 3104705100,Sup_ID = 252 WHERE First_Name= 'Rosy';
UPDATE Internal_Employees SET First_Name = 'Simonette',Last_Name = 'Mintoft',Int_Emp_ID = 253,Email = 'smintoftn@time.com',City = 'Spokane',State = 'Washington',Zip_Code = 99210,Dept_Name = 'Project Management',Dept_Number = 6673,Company_ID = 3104705100,Sup_ID = 253 WHERE First_Name= 'Simonette';
UPDATE Internal_Employees SET First_Name = 'Jo-anne',Last_Name = 'Radenhurst',Int_Emp_ID = 254,Email = 'jradenhursto@sun.com',City = 'Aurora',State = 'Illinois',Zip_Code = 60505,Dept_Name = 'IT',Dept_Number = 6674,Company_ID = 3104705100,Sup_ID = 254 WHERE First_Name= 'Jo-anne';
UPDATE Internal_Employees SET First_Name = 'Sheilakathryn',Last_Name = 'Witchalls',Int_Emp_ID = 255,Email = 'switchallsp@prnewswire.com',City = 'Panama City',State = 'Florida',Zip_Code = 32405,Dept_Name = 'Social Media',Dept_Number = 6675,Company_ID = 3104705100,Sup_ID = 255 WHERE First_Name= 'Sheilakathryn';
UPDATE Internal_Employees SET First_Name = 'Cris',Last_Name = 'Haggidon',Int_Emp_ID = 256,Email = 'chaggidonq@spiegel.de',City = 'Richmond',State = 'Virginia',Zip_Code = 23242,Dept_Name = 'Client Relations Management',Dept_Number = 6676,Company_ID = 3104705100,Sup_ID = 256 WHERE First_Name= 'Cris';
UPDATE Internal_Employees SET First_Name = 'Junia',Last_Name = 'Gimblet',Int_Emp_ID = 257,Email = 'jgimbletr@biglobe.ne.jp',City = 'Bronx',State = 'New York',Zip_Code = 10464,Dept_Name = 'Corporate Communications',Dept_Number = 6677,Company_ID = 3104705100,Sup_ID = 257 WHERE First_Name= 'Junia';
UPDATE Internal_Employees SET First_Name = 'Leoine',Last_Name = 'Lumsdon',Int_Emp_ID = 258,Email = 'llumsdons@blog.com',City = 'Manassas',State = 'Virginia',Zip_Code = 22111,Dept_Name = 'Sourcing',Dept_Number = 6678,Company_ID = 3104705100,Sup_ID = 258 WHERE First_Name= 'Leoine';
UPDATE Internal_Employees SET First_Name = 'Mellicent',Last_Name = 'Spiaggia',Int_Emp_ID = 259,Email = 'mspiaggiat@skype.com',City = 'Pasadena',State = 'California',Zip_Code = 91199,Dept_Name = 'Inspection',Dept_Number = 6679,Company_ID = 3104705100,Sup_ID = 259 WHERE First_Name= 'Mellicent';
UPDATE Internal_Employees SET First_Name = 'Sacha',Last_Name = 'Dulinty',Int_Emp_ID = 260,Email = 'sdulintyu@yolasite.com',City = 'Houston',State = 'Texas',Zip_Code = 77035,Dept_Name = 'Business Development',Dept_Number = 6650,Company_ID = 3104705100,Sup_ID = 230 WHERE First_Name= 'Sacha';
UPDATE Internal_Employees SET First_Name = 'Pedro',Last_Name = 'Ambroise',Int_Emp_ID = 261,Email = 'pambroisev@ocn.ne.jp',City = 'Minneapolis',State = 'Minnesota',Zip_Code = 55487,Dept_Name = 'Creative Services',Dept_Number = 6651,Company_ID = 3104705100,Sup_ID = 231 WHERE First_Name= 'Pedro';
UPDATE Internal_Employees SET First_Name = 'Samaria',Last_Name = 'Tomney',Int_Emp_ID = 262,Email = 'stomneyw@engadget.com',City = 'Fort Worth',State = 'Texas',Zip_Code = 76110,Dept_Name = 'Customer Service',Dept_Number = 6652,Company_ID = 3104705100,Sup_ID = 232 WHERE First_Name= 'Samaria';
UPDATE Internal_Employees SET First_Name = 'Ola',Last_Name = 'Wind',Int_Emp_ID = 263,Email = 'owindx@moonfruit.com',City = 'Pasadena',State = 'Texas',Zip_Code = 77505,Dept_Name = 'Accounting',Dept_Number = 6653,Company_ID = 3104705100,Sup_ID = 233 WHERE First_Name= 'Ola';
UPDATE Internal_Employees SET First_Name = 'Jessalin',Last_Name = 'Oliphand',Int_Emp_ID = 264,Email = 'joliphandy@japanpost.jp',City = 'Beaverton',State = 'Oregon',Zip_Code = 97075,Dept_Name = 'Human Resources',Dept_Number = 6654,Company_ID = 3104705100,Sup_ID = 234 WHERE First_Name= 'Jessalin';
UPDATE Internal_Employees SET First_Name = 'Johan',Last_Name = 'Dolton',Int_Emp_ID = 265,Email = 'jdoltonz@intel.com',City = 'Van Nuys',State = 'California',Zip_Code = 91499,Dept_Name = 'Legal',Dept_Number = 6655,Company_ID = 3104705100,Sup_ID = 235 WHERE First_Name= 'Johan';
UPDATE Internal_Employees SET First_Name = 'Josefina',Last_Name = 'Dionisio',Int_Emp_ID = 266,Email = 'jdionisio10@example.com',City = 'Apache Junction',State = 'Arizona',Zip_Code = 85219,Dept_Name = 'Operations',Dept_Number = 6656,Company_ID = 3104705100,Sup_ID = 236 WHERE First_Name= 'Josefina';
UPDATE Internal_Employees SET First_Name = 'Selestina',Last_Name = 'Cornilleau',Int_Emp_ID = 267,Email = 'scornilleau11@nsw.gov.au',City = 'Boulder',State = 'Colorado',Zip_Code = 80328,Dept_Name = 'Production',Dept_Number = 6657,Company_ID = 3104705100,Sup_ID = 237 WHERE First_Name= 'Selestina';
UPDATE Internal_Employees SET First_Name = 'Darrelle',Last_Name = 'Roxburch',Int_Emp_ID = 268,Email = 'droxburch12@jigsy.com',City = 'San Bernardino',State = 'California',Zip_Code = 92415,Dept_Name = 'Risk Management',Dept_Number = 6658,Company_ID = 3104705100,Sup_ID = 238 WHERE First_Name= 'Darrelle';
UPDATE Internal_Employees SET First_Name = 'Henrik',Last_Name = 'Hallihan',Int_Emp_ID = 269,Email = 'hhallihan13@linkedin.com',City = 'Boulder',State = 'Colorado',Zip_Code = 80310,Dept_Name = 'Marketing',Dept_Number = 6659,Company_ID = 3104705100,Sup_ID = 239 WHERE First_Name= 'Henrik';
UPDATE Internal_Employees SET First_Name = 'Nev',Last_Name = 'Brogi',Int_Emp_ID = 270,Email = 'nbrogi14@bing.com',City = 'Toledo',State = 'Ohio',Zip_Code = 43635,Dept_Name = 'Sales',Dept_Number = 6660,Company_ID = 3104705100,Sup_ID = 240 WHERE First_Name= 'Nev';
UPDATE Internal_Employees SET First_Name = 'Shem',Last_Name = 'Hemeret',Int_Emp_ID = 271,Email = 'shemeret15@spiegel.de',City = 'Los Angeles',State = 'California',Zip_Code = 90081,Dept_Name = 'Technology',Dept_Number = 6661,Company_ID = 3104705100,Sup_ID = 241 WHERE First_Name= 'Shem';
UPDATE Internal_Employees SET First_Name = 'Gabie',Last_Name = 'Btham',Int_Emp_ID = 272,Email = 'gbtham16@java.com',City = 'Shreveport',State = 'Louisiana',Zip_Code = 71115,Dept_Name = 'General Management',Dept_Number = 6662,Company_ID = 3104705100,Sup_ID = 242 WHERE First_Name= 'Gabie';
UPDATE Internal_Employees SET First_Name = 'Rachele',Last_Name = 'Essame',Int_Emp_ID = 273,Email = 'ressame17@imageshack.us',City = 'Jackson',State = 'Mississippi',Zip_Code = 39204,Dept_Name = 'Engineering',Dept_Number = 6663,Company_ID = 3104705100,Sup_ID = 243 WHERE First_Name= 'Rachele';
UPDATE Internal_Employees SET First_Name = 'Renaud',Last_Name = 'Basant',Int_Emp_ID = 274,Email = 'rbasant18@altervista.org',City = 'Suffolk',State = 'Virginia',Zip_Code = 23436,Dept_Name = 'Investor Relations',Dept_Number = 6664,Company_ID = 3104705100,Sup_ID = 244 WHERE First_Name= 'Renaud';
UPDATE Internal_Employees SET First_Name = 'Felita',Last_Name = 'Bodman',Int_Emp_ID = 275,Email = 'fbodman19@g.co',City = 'Madison',State = 'Wisconsin',Zip_Code = 53785,Dept_Name = 'Product Management',Dept_Number = 6665,Company_ID = 3104705100,Sup_ID = 245 WHERE First_Name= 'Felita';
UPDATE Internal_Employees SET First_Name = 'Britt',Last_Name = 'Leathart',Int_Emp_ID = 276,Email = 'bleathart1a@nationalgeographic.com',City = 'Minneapolis',State = 'Minnesota',Zip_Code = 55428,Dept_Name = 'Quality Assurance',Dept_Number = 6666,Company_ID = 3104705100,Sup_ID = 246 WHERE First_Name= 'Britt';
UPDATE Internal_Employees SET First_Name = 'Marthena',Last_Name = 'Tollett',Int_Emp_ID = 277,Email = 'mtollett1b@dagondesign.com',City = 'Richmond',State = 'Virginia',Zip_Code = 23289,Dept_Name = 'Strategic Initiatives & Programs',Dept_Number = 6667,Company_ID = 3104705100,Sup_ID = 247 WHERE First_Name= 'Marthena';
UPDATE Internal_Employees SET First_Name = 'Faunie',Last_Name = 'Pakes',Int_Emp_ID = 278,Email = 'fpakes1c@hao123.com',City = 'Oklahoma City',State = 'Oklahoma',Zip_Code = 73157,Dept_Name = 'Board of Directors',Dept_Number = 6668,Company_ID = 3104705100,Sup_ID = 248 WHERE First_Name= 'Faunie';
UPDATE Internal_Employees SET First_Name = 'Nadeen',Last_Name = 'McFaul',Int_Emp_ID = 279,Email = 'nmcfaul1d@odnoklassniki.ru',City = 'Iowa City',State = 'Iowa',Zip_Code = 52245,Dept_Name = 'Research and Development',Dept_Number = 6669,Company_ID = 3104705100,Sup_ID = 249 WHERE First_Name= 'Nadeen';
UPDATE Internal_Employees SET First_Name = 'Glynda',Last_Name = 'Johns',Int_Emp_ID = 280,Email = 'gjohns1e@github.com',City = 'Tallahassee',State = 'Florida',Zip_Code = 32314,Dept_Name = 'Training',Dept_Number = 6670,Company_ID = 3104705100,Sup_ID = 250 WHERE First_Name= 'Glynda';
UPDATE Internal_Employees SET First_Name = 'Paulita',Last_Name = 'Dumbellow',Int_Emp_ID = 281,Email = 'pdumbellow1f@cam.ac.uk',City = 'Philadelphia',State = 'Pennsylvania',Zip_Code = 19104,Dept_Name = 'Support',Dept_Number = 6671,Company_ID = 3104705100,Sup_ID = 251 WHERE First_Name= 'Paulita';
UPDATE Internal_Employees SET First_Name = 'Arnoldo',Last_Name = 'Hailey',Int_Emp_ID = 282,Email = 'ahailey1g@thetimes.co.uk',City = 'Fredericksburg',State = 'Virginia',Zip_Code = 22405,Dept_Name = 'Asset Management',Dept_Number = 6672,Company_ID = 3104705100,Sup_ID = 252 WHERE First_Name= 'Arnoldo';
UPDATE Internal_Employees SET First_Name = 'Shepperd',Last_Name = 'Benitti',Int_Emp_ID = 283,Email = 'sbenitti1h@liveinternet.ru',City = 'Detroit',State = 'Michigan',Zip_Code = 48295,Dept_Name = 'Project Management',Dept_Number = 6673,Company_ID = 3104705100,Sup_ID = 253 WHERE First_Name= 'Shepperd';
UPDATE Internal_Employees SET First_Name = 'Leslie',Last_Name = 'Jelf',Int_Emp_ID = 284,Email = 'ljelf1i@youku.com',City = 'Topeka',State = 'Kansas',Zip_Code = 66667,Dept_Name = 'IT',Dept_Number = 6674,Company_ID = 3104705100,Sup_ID = 254 WHERE First_Name= 'Leslie';
UPDATE Internal_Employees SET First_Name = 'Chip',Last_Name = 'Lissandrini',Int_Emp_ID = 285,Email = 'clissandrini1j@unblog.fr',City = 'New York City',State = 'New York',Zip_Code = 10150,Dept_Name = 'Social Media',Dept_Number = 6675,Company_ID = 3104705100,Sup_ID = 255 WHERE First_Name= 'Chip';
UPDATE Internal_Employees SET First_Name = 'Teodorico',Last_Name = 'Philippsohn',Int_Emp_ID = 286,Email = 'tphilippsohn1k@reuters.com',City = 'Cincinnati',State = 'Ohio',Zip_Code = 45249,Dept_Name = 'Client Relations Management',Dept_Number = 6676,Company_ID = 3104705100,Sup_ID = 256 WHERE First_Name= 'Teodorico';
UPDATE Internal_Employees SET First_Name = 'Tiffani',Last_Name = 'Eliesco',Int_Emp_ID = 287,Email = 'teliesco1l@nsw.gov.au',City = 'Palm Bay',State = 'Florida',Zip_Code = 32909,Dept_Name = 'Corporate Communications',Dept_Number = 6677,Company_ID = 3104705100,Sup_ID = 257 WHERE First_Name= 'Tiffani';
UPDATE Internal_Employees SET First_Name = 'Lacy',Last_Name = 'Aslen',Int_Emp_ID = 288,Email = 'laslen1m@va.gov',City = 'Mansfield',State = 'Ohio',Zip_Code = 44905,Dept_Name = 'Sourcing',Dept_Number = 6678,Company_ID = 3104705100,Sup_ID = 258 WHERE First_Name= 'Lacy';
UPDATE Internal_Employees SET First_Name = 'Olivette',Last_Name = 'Jandera',Int_Emp_ID = 289,Email = 'ojandera1n@google.cn',City = 'Baton Rouge',State = 'Louisiana',Zip_Code = 70810,Dept_Name = 'Inspection',Dept_Number = 6679,Company_ID = 3104705100,Sup_ID = 259 WHERE First_Name= 'Olivette';
UPDATE Internal_Employees SET First_Name = 'Ewart',Last_Name = 'Sergean',Int_Emp_ID = 290,Email = 'esergean1o@bloomberg.com',City = 'Saint Cloud',State = 'Minnesota',Zip_Code = 56372,Dept_Name = 'Business Development',Dept_Number = 6650,Company_ID = 3104705100,Sup_ID = 230 WHERE First_Name= 'Ewart';
UPDATE Internal_Employees SET First_Name = 'Jamill',Last_Name = 'Trowsdale',Int_Emp_ID = 291,Email = 'jtrowsdale1p@engadget.com',City = 'New York City',State = 'New York',Zip_Code = 10105,Dept_Name = 'Creative Services',Dept_Number = 6651,Company_ID = 3104705100,Sup_ID = 231 WHERE First_Name= 'Jamill';
UPDATE Internal_Employees SET First_Name = 'Fletch',Last_Name = 'Pedro',Int_Emp_ID = 292,Email = 'fpedro1q@jalbum.net',City = 'Fort Worth',State = 'Texas',Zip_Code = 76147,Dept_Name = 'Customer Service',Dept_Number = 6652,Company_ID = 3104705100,Sup_ID = 232 WHERE First_Name= 'Fletch';
UPDATE Internal_Employees SET First_Name = 'Melanie',Last_Name = 'Gawne',Int_Emp_ID = 293,Email = 'mgawne1r@vimeo.com',City = 'El Paso',State = 'Texas',Zip_Code = 79994,Dept_Name = 'Accounting',Dept_Number = 6653,Company_ID = 3104705100,Sup_ID = 233 WHERE First_Name= 'Melanie';
UPDATE Internal_Employees SET First_Name = 'Kimberly',Last_Name = 'Petschel',Int_Emp_ID = 294,Email = 'kpetschel1s@mashable.com',City = 'Tacoma',State = 'Washington',Zip_Code = 98442,Dept_Name = 'Human Resources',Dept_Number = 6654,Company_ID = 3104705100,Sup_ID = 234 WHERE First_Name= 'Kimberly';
UPDATE Internal_Employees SET First_Name = 'Mariana',Last_Name = 'Fardon',Int_Emp_ID = 295,Email = 'mfardon1t@altervista.org',City = 'Miami',State = 'Florida',Zip_Code = 33261,Dept_Name = 'Legal',Dept_Number = 6655,Company_ID = 3104705100,Sup_ID = 235 WHERE First_Name= 'Mariana';
UPDATE Internal_Employees SET First_Name = 'Lydon',Last_Name = 'Beckitt',Int_Emp_ID = 296,Email = 'lbeckitt1u@blogger.com',City = 'Metairie',State = 'Louisiana',Zip_Code = 70005,Dept_Name = 'Operations',Dept_Number = 6656,Company_ID = 3104705100,Sup_ID = 236 WHERE First_Name= 'Lydon';
UPDATE Internal_Employees SET First_Name = 'Zacharias',Last_Name = 'Yoselevitch',Int_Emp_ID = 297,Email = 'zyoselevitch1v@shinystat.com',City = 'New Orleans',State = 'Louisiana',Zip_Code = 70183,Dept_Name = 'Production',Dept_Number = 6657,Company_ID = 3104705100,Sup_ID = 237 WHERE First_Name= 'Zacharias';
UPDATE Internal_Employees SET First_Name = 'Danny',Last_Name = 'Wickrath',Int_Emp_ID = 298,Email = 'dwickrath1w@weibo.com',City = 'New York City',State = 'New York',Zip_Code = 10125,Dept_Name = 'Risk Management',Dept_Number = 6658,Company_ID = 3104705100,Sup_ID = 238 WHERE First_Name= 'Danny';
UPDATE Internal_Employees SET First_Name = 'Tate',Last_Name = 'Fiddiman',Int_Emp_ID = 299,Email = 'tfiddiman1x@netlog.com',City = 'Albuquerque',State = 'New Mexico',Zip_Code = 87190,Dept_Name = 'Marketing',Dept_Number = 6659,Company_ID = 3104705100,Sup_ID = 239 WHERE First_Name= 'Tate';
UPDATE Internal_Employees SET First_Name = 'Lillian',Last_Name = 'Vearncomb',Int_Emp_ID = 300,Email = 'lvearncomb1y@goo.ne.jp',City = 'Fairbanks',State = 'Alaska',Zip_Code = 99709,Dept_Name = 'Sales',Dept_Number = 6660,Company_ID = 3104705100,Sup_ID = 240 WHERE First_Name= 'Lillian';
UPDATE Internal_Employees SET First_Name = 'Maddy',Last_Name = 'Takos',Int_Emp_ID = 301,Email = 'mtakos1z@jigsy.com',City = 'Montgomery',State = 'Alabama',Zip_Code = 36119,Dept_Name = 'Technology',Dept_Number = 6661,Company_ID = 3104705100,Sup_ID = 241 WHERE First_Name= 'Maddy';
UPDATE Internal_Employees SET First_Name = 'Pen',Last_Name = 'Buxey',Int_Emp_ID = 302,Email = 'pbuxey20@phoca.cz',City = 'South Bend',State = 'Indiana',Zip_Code = 46634,Dept_Name = 'General Management',Dept_Number = 6662,Company_ID = 3104705100,Sup_ID = 242 WHERE First_Name= 'Pen';
UPDATE Internal_Employees SET First_Name = 'Jard',Last_Name = 'Dawes',Int_Emp_ID = 303,Email = 'jdawes21@google.pl',City = 'Chicago',State = 'Illinois',Zip_Code = 60663,Dept_Name = 'Engineering',Dept_Number = 6663,Company_ID = 3104705100,Sup_ID = 243 WHERE First_Name= 'Jard';
UPDATE Internal_Employees SET First_Name = 'Berget',Last_Name = 'Pennycuick',Int_Emp_ID = 304,Email = 'bpennycuick22@hp.com',City = 'Austin',State = 'Texas',Zip_Code = 78769,Dept_Name = 'Investor Relations',Dept_Number = 6664,Company_ID = 3104705100,Sup_ID = 244 WHERE First_Name= 'Berget';
UPDATE Internal_Employees SET First_Name = 'Reese',Last_Name = 'De la Yglesia',Int_Emp_ID = 305,Email = 'rdelayglesia23@nhs.uk',City = 'Inglewood',State = 'California',Zip_Code = 90310,Dept_Name = 'Product Management',Dept_Number = 6665,Company_ID = 3104705100,Sup_ID = 245 WHERE First_Name= 'Reese';
UPDATE Internal_Employees SET First_Name = 'Sharon',Last_Name = 'O''Loghlen',Int_Emp_ID = 306,Email = 'sologhlen24@jigsy.com',City = 'Kansas City',State = 'Missouri',Zip_Code = 64153,Dept_Name = 'Quality Assurance',Dept_Number = 6666,Company_ID = 3104705100,Sup_ID = 246 WHERE First_Name= 'Sharon';
UPDATE Internal_Employees SET First_Name = 'Karlik',Last_Name = 'Barnhart',Int_Emp_ID = 307,Email = 'kbarnhart25@altervista.org',City = 'Pittsburgh',State = 'Pennsylvania',Zip_Code = 15230,Dept_Name = 'Strategic Initiatives & Programs',Dept_Number = 6667,Company_ID = 3104705100,Sup_ID = 247 WHERE First_Name= 'Karlik';
UPDATE Internal_Employees SET First_Name = 'Aleda',Last_Name = 'Clissett',Int_Emp_ID = 308,Email = 'aclissett26@seesaa.net',City = 'Chandler',State = 'Arizona',Zip_Code = 85246,Dept_Name = 'Board of Directors',Dept_Number = 6668,Company_ID = 3104705100,Sup_ID = 248 WHERE First_Name= 'Aleda';
UPDATE Internal_Employees SET First_Name = 'Lacey',Last_Name = 'Arsmith',Int_Emp_ID = 309,Email = 'larsmith27@paginegialle.it',City = 'Denver',State = 'Colorado',Zip_Code = 80299,Dept_Name = 'Research and Development',Dept_Number = 6669,Company_ID = 3104705100,Sup_ID = 249 WHERE First_Name= 'Lacey';
UPDATE Internal_Employees SET First_Name = 'Anestassia',Last_Name = 'Le Provost',Int_Emp_ID = 310,Email = 'aleprovost28@vkontakte.ru',City = 'Louisville',State = 'Kentucky',Zip_Code = 40210,Dept_Name = 'Training',Dept_Number = 6670,Company_ID = 3104705100,Sup_ID = 250 WHERE First_Name= 'Anestassia';
UPDATE Internal_Employees SET First_Name = 'Cathe',Last_Name = 'McDarmid',Int_Emp_ID = 311,Email = 'cmcdarmid29@columbia.edu',City = 'Winston Salem',State = 'North Carolina',Zip_Code = 27110,Dept_Name = 'Support',Dept_Number = 6671,Company_ID = 3104705100,Sup_ID = 251 WHERE First_Name= 'Cathe';
UPDATE Internal_Employees SET First_Name = 'Netty',Last_Name = 'Baskwell',Int_Emp_ID = 312,Email = 'nbaskwell2a@jimdo.com',City = 'Portsmouth',State = 'New Hampshire',Zip_Code = 3804,Dept_Name = 'Asset Management',Dept_Number = 6672,Company_ID = 3104705100,Sup_ID = 252 WHERE First_Name= 'Netty';
UPDATE Internal_Employees SET First_Name = 'Lula',Last_Name = 'Westlake',Int_Emp_ID = 313,Email = 'lwestlake2b@princeton.edu',City = 'Little Rock',State = 'Arkansas',Zip_Code = 72215,Dept_Name = 'Project Management',Dept_Number = 6673,Company_ID = 3104705100,Sup_ID = 253 WHERE First_Name= 'Lula';
UPDATE Internal_Employees SET First_Name = 'Lucita',Last_Name = 'Rowet',Int_Emp_ID = 314,Email = 'lrowet2c@yellowbook.com',City = 'Jacksonville',State = 'Florida',Zip_Code = 32225,Dept_Name = 'IT',Dept_Number = 6674,Company_ID = 3104705100,Sup_ID = 254 WHERE First_Name= 'Lucita';
UPDATE Internal_Employees SET First_Name = 'Angil',Last_Name = 'Ashbolt',Int_Emp_ID = 315,Email = 'aashbolt2d@chron.com',City = 'Houston',State = 'Texas',Zip_Code = 77075,Dept_Name = 'Social Media',Dept_Number = 6675,Company_ID = 3104705100,Sup_ID = 255 WHERE First_Name= 'Angil';
UPDATE Internal_Employees SET First_Name = 'Tod',Last_Name = 'Paige',Int_Emp_ID = 316,Email = 'tpaige2e@altervista.org',City = 'Fresno',State = 'California',Zip_Code = 93794,Dept_Name = 'Client Relations Management',Dept_Number = 6676,Company_ID = 3104705100,Sup_ID = 256 WHERE First_Name= 'Tod';
UPDATE Internal_Employees SET First_Name = 'Udale',Last_Name = 'Gatling',Int_Emp_ID = 317,Email = 'ugatling2f@wikispaces.com',City = 'Los Angeles',State = 'California',Zip_Code = 90035,Dept_Name = 'Corporate Communications',Dept_Number = 6677,Company_ID = 3104705100,Sup_ID = 257 WHERE First_Name= 'Udale';
UPDATE Internal_Employees SET First_Name = 'Eulalie',Last_Name = 'Dowzell',Int_Emp_ID = 318,Email = 'edowzell2g@cdbaby.com',City = 'Fresno',State = 'California',Zip_Code = 93726,Dept_Name = 'Sourcing',Dept_Number = 6678,Company_ID = 3104705100,Sup_ID = 258 WHERE First_Name= 'Eulalie';
UPDATE Internal_Employees SET First_Name = 'Cordelie',Last_Name = 'Couves',Int_Emp_ID = 319,Email = 'ccouves2h@telegraph.co.uk',City = 'Roanoke',State = 'Virginia',Zip_Code = 24040,Dept_Name = 'Inspection',Dept_Number = 6679,Company_ID = 3104705100,Sup_ID = 259 WHERE First_Name= 'Cordelie';
UPDATE Internal_Employees SET First_Name = 'Maggie',Last_Name = 'Cowterd',Int_Emp_ID = 320,Email = 'mcowterd2i@pbs.org',City = 'Saint Paul',State = 'Minnesota',Zip_Code = 55188,Dept_Name = 'Business Development',Dept_Number = 6650,Company_ID = 3104705100,Sup_ID = 230 WHERE First_Name= 'Maggie';
UPDATE Internal_Employees SET First_Name = 'Jemmy',Last_Name = 'Fanthome',Int_Emp_ID = 321,Email = 'jfanthome2j@whitehouse.gov',City = 'El Paso',State = 'Texas',Zip_Code = 79968,Dept_Name = 'Creative Services',Dept_Number = 6651,Company_ID = 3104705100,Sup_ID = 231 WHERE First_Name= 'Jemmy';
UPDATE Internal_Employees SET First_Name = 'Warner',Last_Name = 'Linke',Int_Emp_ID = 322,Email = 'wlinke2k@wikia.com',City = 'Bryan',State = 'Texas',Zip_Code = 77806,Dept_Name = 'Customer Service',Dept_Number = 6652,Company_ID = 3104705100,Sup_ID = 232 WHERE First_Name= 'Warner';
UPDATE Internal_Employees SET First_Name = 'Samuel',Last_Name = 'Nyssens',Int_Emp_ID = 323,Email = 'snyssens2l@msu.edu',City = 'Fort Lauderdale',State = 'Florida',Zip_Code = 33345,Dept_Name = 'Accounting',Dept_Number = 6653,Company_ID = 3104705100,Sup_ID = 233 WHERE First_Name= 'Samuel';
UPDATE Internal_Employees SET First_Name = 'Talbert',Last_Name = 'Confait',Int_Emp_ID = 324,Email = 'tconfait2m@howstuffworks.com',City = 'Montgomery',State = 'Alabama',Zip_Code = 36134,Dept_Name = 'Human Resources',Dept_Number = 6654,Company_ID = 3104705100,Sup_ID = 234 WHERE First_Name= 'Talbert';
UPDATE Internal_Employees SET First_Name = 'Ginevra',Last_Name = 'Flawn',Int_Emp_ID = 325,Email = 'gflawn2n@blogtalkradio.com',City = 'Baltimore',State = 'Maryland',Zip_Code = 21275,Dept_Name = 'Legal',Dept_Number = 6655,Company_ID = 3104705100,Sup_ID = 235 WHERE First_Name= 'Ginevra';
UPDATE Internal_Employees SET First_Name = 'Carrissa',Last_Name = 'Beushaw',Int_Emp_ID = 326,Email = 'cbeushaw2o@cmu.edu',City = 'Milwaukee',State = 'Wisconsin',Zip_Code = 53215,Dept_Name = 'Operations',Dept_Number = 6656,Company_ID = 3104705100,Sup_ID = 236 WHERE First_Name= 'Carrissa';
UPDATE Internal_Employees SET First_Name = 'Willey',Last_Name = 'Beesley',Int_Emp_ID = 327,Email = 'wbeesley2p@xing.com',City = 'Homestead',State = 'Florida',Zip_Code = 33034,Dept_Name = 'Production',Dept_Number = 6657,Company_ID = 3104705100,Sup_ID = 237 WHERE First_Name= 'Willey';
UPDATE Internal_Employees SET First_Name = 'Wallas',Last_Name = 'Itzkin',Int_Emp_ID = 328,Email = 'witzkin2q@privacy.gov.au',City = 'Omaha',State = 'Nebraska',Zip_Code = 68117,Dept_Name = 'Risk Management',Dept_Number = 6658,Company_ID = 3104705100,Sup_ID = 238 WHERE First_Name= 'Wallas';
UPDATE Internal_Employees SET First_Name = 'Aindrea',Last_Name = 'Landsbury',Int_Emp_ID = 329,Email = 'alandsbury2r@webmd.com',City = 'New York City',State = 'New York',Zip_Code = 10270,Dept_Name = 'Marketing',Dept_Number = 6659,Company_ID = 3104705100,Sup_ID = 239 WHERE First_Name= 'Aindrea';
